// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJQlSqgrUoSTTR2rAK-IOB2FLBrnE4Jw',
    appId: '1:600601673824:web:2b1cb1faa38267302ac305',
    messagingSenderId: '600601673824',
    projectId: 'gamereview-d076d',
    authDomain: 'gamereview-d076d.firebaseapp.com',
    storageBucket: 'gamereview-d076d.appspot.com',
    measurementId: 'G-SHV9YKQQ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSXyHPlErfqvaSsBid6BbCikQzJQtuOqo',
    appId: '1:600601673824:android:35d38f186edb59462ac305',
    messagingSenderId: '600601673824',
    projectId: 'gamereview-d076d',
    storageBucket: 'gamereview-d076d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy273QfJMJOTStluAZpi1VyLuUJq0zPDY',
    appId: '1:600601673824:ios:57fe1bf0d8c814692ac305',
    messagingSenderId: '600601673824',
    projectId: 'gamereview-d076d',
    storageBucket: 'gamereview-d076d.appspot.com',
    androidClientId: '600601673824-8df3pj4nl5otgt4jqrpgl6tt7kefi9gg.apps.googleusercontent.com',
    iosClientId: '600601673824-dmi9mt68umbr9h9vu5nbo17r9ito3h8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameReviews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy273QfJMJOTStluAZpi1VyLuUJq0zPDY',
    appId: '1:600601673824:ios:57fe1bf0d8c814692ac305',
    messagingSenderId: '600601673824',
    projectId: 'gamereview-d076d',
    storageBucket: 'gamereview-d076d.appspot.com',
    androidClientId: '600601673824-8df3pj4nl5otgt4jqrpgl6tt7kefi9gg.apps.googleusercontent.com',
    iosClientId: '600601673824-dmi9mt68umbr9h9vu5nbo17r9ito3h8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameReviews',
  );
}
